#!/bin/sh

dbname=$1

if [ "${dbname}" = '' ] ; then
    dbname=monitorel_worker
fi

if mysqladmin -uroot create $dbname ; then
    echo "Init database: ${dbname}"
    mysql -uroot $dbname < db/schema_theschwartz.sql
fi
